### ISSUE TITLE
06A Construct ZCTA pairs by state

### ISSUE THREAD

**Issue by geowcz** [everknight/LargeODcost#11]
![image](https://user-images.githubusercontent.com/52430000/95279514-80ea2d00-0818-11eb-8659-9b1478010b17.png)

**Comment by geowcz** [comment]
The output only has the values of OZCTA, DZCTA, olat, olong, dlat, dlong. There are no values for the travel time and distance.

**Comment by everknight** [comment]
You will have to use the ZCTA points file ZCTA PWS for whole US (specifically, this file: ZCTA_Pop_weighted_Centroid_2010_Snap_state). The selected 200 zctas don't have a field for state name.
