### ISSUE TITLE
Output OD flows from 03.5 Get Google Distance Matrix

### ISSUE THREAD

**Issue by geowcz** [everknight/LargeODcost#5]
I tried a layer with five features, the output table only returns five records with the identical originID and destinationID, see below:

OBJECTID, OBJECTID, TimeCost, Distance
1, 1, 1 min, 1 m
2, 2, 1 min, 1 m
3, 3, 1 min, 1 m
4, 4, 1 min, 1 m
5, 5, 1 min, 1 m

I think this tool is designed to derive N*N records. In my case, it should be 5*5= 25 or 5*4 =20 as Google sometimes can not calculate the distance from one point to itself, right?

**Comment by everknight** [comment]
This tool is designed to work with the OD pair instead of zcta file. 
Please use tool 06A or 06B to costruct your zcta pairs.
