### ISSUE TITLE
00 Set Default Network Setting

### ISSUE THREAD

**Issue by geowcz** [everknight/LargeODcost#8]
The restrictions need an input from users, is there any example to show how to define it?

**Comment by geowcz** [comment]
I added Optional on the side of restrictions and use hierarchy. but still need an example to show to use these two options. Could you provide one?

**Comment by everknight** [comment]
Thank you for adding Optional. These options are available when a user have an advanced road network. 
With advanced road network, after you added the path from the previous parameter, it will be automatically populated.
